version: '3'
services:
  server: 
    image: node:12.18.4 
    working_dir: /code
    ports:
      - '3000:3000'
    environment: 
      - PGUSER=bloguser
      - PGHOST=db
      - PGPASSWORD=blogpass
      - PGDATABASE=blog
      - PGPORT=5432
    volumes:
      - type: bind
        source: ./server
        target: /code
    depends_on:
      - db
    command: bash -c "npm install && npm run dev"
  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=blog
      - POSTGRES_USER=bloguser
      - POSTGRES_PASSWORD=blogpass
volumes:
  dbdata:
